const userEndpoints = {
  signup: "/users",
  signupVerification: "/users/verify-otp",
  resendVerification:"/users/resend-otp",
  login: "/auth/users/login",
  logout: "/auth/users/logout",
  profile: "/users",
  getUser:'/users',
  updateProfile: "/users",
  uploadId:'/users',
  roomDetail:'/users/listings',
  usergetChat:'/chat',
  getListings: "/users/host/listings",
  addRoom: "/users/host/listings",
  getAmenities:'/users/amenities',
  getCategory:'/users/category',
  roomData:"/users/host/listings",
  unlist: "/users/host/listings",
  roomDataUpdate:"/users/host/listings",
  homeListings:"/users/listings",
  addtoWishlist:'/users/wishlist',
  getWishlist: '/users/wishlist',
  userWishlists:'/users/wishlist',
  removeWishlist:'/users/wishlist',
  searchListing: "/users/listings",
  hostgetChat:'/users/host/chat',
  hostNewconversation:'/users/host/chat',
  addMessage:'/users/host/chat/messages',
  getMessage:'/users/host/chat/messages',
  getBookings: '/users/bookings',
  canceledBookings: '/users/bookings/cancelled',
  cancelBooking:'/users/bookings',
  checkDateAvailability:'/users/bookings/check-availability',
  payment:'/users/bookings',
  blockDates:'/users/host/managedate',
  blockedDates:'/users/host/managedate',
  removeDates:'/users/host/managedate',
  upBookings:'/users/host/bookings',
  canBookings:'users/host/bookings',
  hsotcancelBooking:'/users/host/bookings',
  hostconfirmBooking:'users/host/bookigs'
};

export default userEndpoints;
